### ISSUE TITLE
Split cookbooks

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum-documentation#101]
The cookbook : http://docs.atoum.org/fr/latest/cookbook.html

I'm wondering if it will not be better to split the cookbooks in multiple file or parts. We' have, right now: * stuff about using it with a some tools (behat, continous integration, ...)
* stuff about using it with some frameworks
* some receipt like testing singleton
* some other stuff like optimising PHP

The two last for, me must stay in cookbook at the moment, but the other should be externalized.

**Comment by marmotz** [comment]
Split like assertions file (point of view of doc writer) ?
Or split in different pages (point of view of doc reader) ?

**Comment by Grummfy** [comment]
Both, depending of what you think is more relevant.

**Comment by marmotz** [comment]
In my opinion, it's usefull for writers to cut big files like i did for assertions.

I don't think this is usefull for readers, the left menu help readers.

It's only my humble opinion

**Comment by Grummfy** [comment]
oki, thanks.
I will split files but keep in one page
