### ISSUE TITLE
Section title missing in cookbook

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum-documentation#102]
Since I have adding some top layer in cookbook, there is missing title (zend famwork symfony, etc ... ) they are not visible any more.

**Comment by marmotz** [comment]
I see it in french and english doc

**Comment by Grummfy** [comment]
> Utilisation avec des frameworks
> Étape 1 : Installation d’atoum au sein d’eZ Publish
=> https://github.com/atoum/atoum-documentation/blob/master/source/fr/cookbook.rst#L475
the title "Utilisation avec ez Publish" is missing

**Comment by marmotz** [comment]
_ is not a valid

see the top of https://raw.githubusercontent.com/atoum/atoum-documentation/master/source/fr/index.rst

**Comment by Grummfy** [comment]
*#**@**-*

bon je corrigerait
