### ISSUE TITLE
@dataProvider  missing documentation

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum-documentation#112]
There is no document about @dataProvider could you please explaion or give example?

ping @Hywan , @jubianchi , @mageekguy

**Comment by marmotz** [comment]
fr: http://docs.atoum.org/fr/latest/aide_ecriture.html#fournisseurs-de-donnees-data-provider
en: http://atoum.readthedocs.org/en/latest/written_help.html#data-providers

**Comment by Grummfy** [comment]
Not closed => http://docs.atoum.org/fr/latest/aide_ecriture.html#dataprovider

**Comment by marmotz** [comment]
In my opinion, you should remove this section or add a link to the previous documentation, or move the first documentation in this section...
