### ISSUE TITLE
Upgrade mock part of the documentation

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum-documentation#116]
Compelte the mock documentation with some new feature :  http://jubianchi.fr/atoum-mock-pleaz.htm

- [x] http://jubianchi.fr/atoum-mock-pleaz.htm (https://web.archive.org/web/20160324010649/http://jubianchi.fr/atoum-mock-pleaz.htm)
- [x] #69
- [x] #131
- [x] #37
- [x] #61
- [x] #164
- [x] atoum/atoum#496

**Comment by jubianchi** [comment]
New feature around mocks: https://github.com/atoum/atoum/pull/496

**Comment by Grummfy** [comment]
see also #69 , #131 and #61 for doc related to mocks
