### ISSUE TITLE
English as default language?

### ISSUE THREAD

**Issue by mageekguy** [atoum/atoum-documentation#128]
Currently, the default language is french.
I think that a better strategy is to define english as default language, because currently, all english traffic is lost according to google analytics.
And it may be interesting to use the HTTP header `accept-language` to serve the best language to the user, but i'm not sure that it's technically possible.

**Comment by CedCannes** [comment]
:+1:

**Comment by vonglasow** [comment]
:+1:

**Comment by Grummfy** [comment]
:+1:

**Comment by jubianchi** [comment]
:+1:

**Comment by SebastienElet** [comment]
:+1:

**Comment by marmotz** [comment]
Firstly, as I'm the only owner of the readthedocs projects, I think it's a good idea to have at least one another.
Who wants ~~to live forever~~ to maintain readthedocs projects with me ?

I could define english as the default language, but readthedocs doesn't allow to automatically display the best language according to http headers.
You should create an issue on their github (https://github.com/rtfd/readthedocs.org)

**Comment by Grummfy** [comment]
Marmotz I can help on RTD if you want and other agree

**Comment by Grummfy** [comment]
it's done, I forget to close this issue
