### ISSUE TITLE
Update RTD configurations

### ISSUE THREAD

**Issue by marmotz** [atoum/atoum-documentation#129]
see https://github.com/rtfd/readthedocs.org/issues/1009

**Comment by Grummfy** [comment]
thanks to link it. I will check tonight.

**Comment by Grummfy** [comment]
well except that now the doc point on the english nothing change ....

for information I also create this : https://github.com/rtfd/readthedocs.org/issues/1715

**Comment by marmotz** [comment]
So reopen RTD ticket or ask precisions :-/
