### ISSUE TITLE
constant asserter : missing documentation

### ISSUE THREAD

**Issue by agallou** [atoum/atoum-documentation#156]
there is no documentation for the constant asserter.

it has an isEqualTo (and equalTo) method :

And seems to be used like this : 

```
$this->constant(GLOB_NOSORT)->isEqualTo(4);
```

I don't really see the use case here. There is no check on wether it's a constant or not. So why not using the string/float/asserters ? 

Is it just for the sematic ? (should we reflect that on the documentation ?) // ping @atoum/all

**Comment by marmotz** [comment]
That's good questions

**Comment by Grummfy** [comment]
ping @jubianchi

**Comment by Grummfy** [comment]
ping @jubianchi @Hywan

**Comment by Grummfy** [comment]
ping @jubianchi @Hywan
