### ISSUE TITLE
extension asserter : missing documentation

### ISSUE THREAD

**Issue by agallou** [atoum/atoum-documentation#157]
There is no documentation on the extension asserter.

It could be use like this : 

```
$this->extension('json')->isLoaded();
```

That will trigger an error if the json extension is not loaded.

We can achieve the same with the `@extensions` tag and the `--fail-if-skipped-methods`.

Is the extension asserter deprecated ? should it be documented ? // ping @atoum/all

**Comment by Grummfy** [comment]
ping @jubianchi
