### ISSUE TITLE
New resource asserter

### ISSUE THREAD

**Issue by jubianchi** [atoum/atoum-documentation#165]
See atoum/atoum#535

``` php
$this
    ->resource($variable)
        ->isOfType('stream')
        ->isStream()
        ->type
            ->isEqualTo('stream')
;
```

Both assertions are equivalent here. To sum-up:
- the `phpResource` asserter is aliased to `resource`
- `phpResource:: isOfType()` will compare the type of the given resource against a string (`->isOfType('stream')`)
- `phpResource:: is*()` will match the type of the stream against a pattern computed from the method name: `->isFooBar()` will try to match a stream with type `foo bar`, `fooBar`, `foo_bar`, ...
- `phpResource::$type` is an helper providing a string asserter on the stream type so that the user can do things like `->type->matches('/foo.*bar/')`

**Comment by Hywan** [comment]
Yup, `->type` fallbacks to the `string` asserters.

**Comment by Grummfy** [comment]
not sure to understand this. you speak about stream but it's resource, not stream...
