### ISSUE TITLE
Documentation sur /phing/AtoumTask.php manquante

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum-documentation#189]

**Comment by shulard** [comment]
Hello I'm looking at this issue, where do you think it'll be the best place to put that documentation ? Do I need to create a new cookbook file about phing (like the jenkins one) and import it everywhere ?

**Comment by Grummfy** [comment]
I will add it in cookbook , so yes in tools/outils part.

**Comment by shulard** [comment]
Ok I'll do that 😄
