### ISSUE TITLE
[Locale FR] "Mocking systems" should be in French

### ISSUE THREAD

**Issue by Oliboy50** [atoum/atoum-documentation#196]
I think it's a regression since I'm pretty sure this part of the documentation was in french before.

http://docs.atoum.org/fr/latest/mocking_systems.html

**Comment by Grummfy** [comment]
yep, totally, with a lot of other parts. It's because we put the main language as english and inside the translation system we use (crowdin) there is no way to put translated files directly, so we need to restart it from scratch...
