### ISSUE TITLE
[Theme] search input design

### ISSUE THREAD

**Issue by marmotz** [atoum/atoum-documentation#204]
atoum website design is based on square but search input have round corners.

I think it's not smooth. But it's only my opinion.

What do you think ?

**Comment by Grummfy** [comment]
honestly, for me it's the same .... perhaps @agallou or @Hywan can come with some input?

**Comment by marmotz** [comment]
Just remove border-radius in .wy-side-nav-search input[type=text]

I don't find file to edit and propose PR, sorry.
