### ISSUE TITLE
add warning in first step for ide

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum-documentation#227]
Adding a note or a warning to help people who would like to follow the [first steps](http://docs.atoum.org/en/latest/first_test.html) with atoum that if they try with an ide, the will have warning. So recommend to install the extension atoum-stubs.

**Comment by Niharika29** [comment]
It'd be nice to have more precise information on this task. Current description is not very helpful. Where should the note be added?

**Comment by Grummfy** [comment]
In the page http://docs.atoum.org/en/latest/first_test.html => https://github.com/atoum/atoum-documentation/blob/master/source/en/first_test.rst
