### ISSUE TITLE
adding a comment about atoum wording

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum-documentation#243]
adding somewhere about the wording of atoum (no caps at first letter)

**Comment by Grummfy** [comment]
@jubianchi @Hywan @mikaelrandy @agallou I know that we should write atoum in lowercase, but is it really important? nobody respect that rule and honestly I don't care. so we drop it?

**Comment by mikaelrandy** [comment]
I agree with @Grummfy on both points : 
- if we choose to keep specific capitalization about atoum, we should explain it
- but do we still keep this specificity ?

**Comment by Grummfy** [comment]
let's forget the wording, so I close it
