### ISSUE TITLE
Missing "castToArray" asserter documentation

### ISSUE THREAD

**Issue by mikaelrandy** [atoum/atoum-documentation#260]
The asserter [castToArray](https://github.com/atoum/atoum/blob/master/classes/asserters/castToArray.php) is not documented.

We should add a specific documentation for this asserter

**Comment by Grummfy** [comment]
If you can elaborate a bit more, because like this no everybody can help

**Comment by mikaelrandy** [comment]
It was a reminder while a wrote another documentation

**Comment by Grummfy** [comment]
ping @mikaelrandy

**Comment by mikaelrandy** [comment]
I'll try to work on it next week-end

**Comment by Grummfy** [comment]
thanks
