### ISSUE TITLE
shuntParentClassCalls documentation

### ISSUE THREAD

**Issue by b-viguier** [atoum/atoum-documentation#37]
According to the current (french) [documentation](http://docs.atoum.org/fr/chapitre2.html#Shunter-les-appels-aux-methodes-parentes), it is not clear to know if we have to call `shuntParentClassCalls` each time we create a mock or not. Here a surprising example for me:

``` php
//2 classes to test
class A {
    public function __construct() {
        trigger_error("Error A");
    }
}

class B {
    public function __construct() {
        trigger_error("Error B");
    }
}
...
//Now for the test, we want to mock classes above, but without calling constructor
public function test_shunt() {
        //We need to shunt constructor call
        $this->mockGenerator->shuntParentClassCalls();
        new \mock\A;
        //Don't needed again
        new \mock\A;
        //... but for a new class (I guess?), it is needed again
        $this->mockGenerator->shuntParentClassCalls();
        new \mock\B;
        //don't need...
        new \mock\B;
        //don't need...
        new \mock\A;
}
```

I guess that the mock generator work differently according to the class to mock, but IMHO it is not clear according to the documentation... or if it is not a feature, it is a bug :)

Thanks for your work!

**Comment by bertrandjamin** [comment]
FYI, I have encountered the same issue with the `orphanize` method. 
It could be interesting to add the same note (https://github.com/atoum/atoum-documentation/compare/master...Grummfy:fix_37#diff-f08c1881f1aaa0bc58353d50958c5068R124)  for this  part.
Or make this note more global for all the mockGenerator part ?

**Comment by Grummfy** [comment]
a lot need improvements on tis part, I need to finished it with overall clear example (and this is the most difficult part in this one)
