### ISSUE TITLE
Does function `afterDestructionOf` still exist?

### ISSUE THREAD

**Issue by b-viguier** [atoum/atoum-documentation#39]
The function `afterDesctructionOf` is referenced in the documentation here: [http://docs.atoum.org/fr/chapitre2.html#afterDestructionOf](http://docs.atoum.org/fr/chapitre2.html#afterDestructionOf)

... but I cannot find its definition in sources... Is it deprecated?

**Comment by Grummfy** [comment]
@b-viguier the readme file as be created and explain how to contribute, if you still want to.

**Comment by Grummfy** [comment]
this can be closed ping @marmotz
