### ISSUE TITLE
Port posts from atoum wiki

### ISSUE THREAD

**Issue by jubianchi** [atoum/atoum-documentation#45]
* [ ] https://github.com/atoum/atoum/wiki/atoum-et-Behat
* [ ] https://github.com/atoum/atoum/wiki/Lancer-un-ensemble-de-test-en-une-commande
* [ ] https://github.com/atoum/atoum/wiki/Optimiser-PHP-pour-ex%C3%A9cuter-les-tests-le-plus-rapidement-possible
* [ ] https://github.com/atoum/atoum/wiki/Ressources-et-tutoriaux
* [ ] https://github.com/atoum/atoum/wiki/Utiliser-atoum-avec-eZ-publish

**Comment by Grummfy** [comment]
I don't see where to put https://github.com/atoum/atoum/wiki/Lancer-un-ensemble-de-test-en-une-commande for me i slaready there in the command line part.

I'm wondering if we should not create a new section for https://github.com/atoum/atoum/wiki/Ressources-et-tutoriaux . @marmotz your advice on this one?

**Comment by marmotz** [comment]
At first the cookbook section had been thought for this purpose

**Comment by Grummfy** [comment]
But for externals links, we add it to cookbook or we create a dedicated page?

**Comment by marmotz** [comment]
Yeah for external links, we should add "Ressources externes à propos d'atoum" / "External resources about atoum" pages
