### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by marmotz** [atoum/atoum-documentation#58]

**Comment by Grummfy** [comment]
I think to this one : http://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by marmotz** [comment]
+1

**Comment by Grummfy** [comment]
I will like to have other comment from @jubianchi , @Hywan , @mageekguy, @vonglasow, ...

**Comment by Grummfy** [comment]
So @Hywan @jubianchi @mageekguy @vonglasow no input? So you agree on this?

**Comment by vonglasow** [comment]
@Grummfy @marmotz, this looks good!

**Comment by mageekguy** [comment]
FYI atom use the BSD licence.

**Comment by Hywan** [comment]
Why not BSD-2?

**Comment by Grummfy** [comment]
Like explain on IRC, we need a license.
But for documentation, code license is not so well adapted. And the http://creativecommons.org/licenses/by-nc-sa/4.0/ is well adapted, but if most of you want BSD, let's go bsd ... 

So I propose this :
* BSD 2
* CC BY-NC-SA 4.0 : :+1: 
* Other
