### ISSUE TITLE
Assertions without parenthesis

### ISSUE THREAD

**Issue by jubianchi** [atoum/atoum-documentation#65]
We should document the fact that assertion without required argument do not either require parenthesis. For example:

```php
<?php

$this->integer(0)->isZero()
```

Could also be written:

```php
<?php

$this->integer(0)->isZero
```

This applies to:

* https://github.com/atoum/atoum/blob/master/classes/asserters/adapter.php#L20-L21
* https://github.com/atoum/atoum/blob/master/classes/asserters/boolean.php#L16-L17
* https://github.com/atoum/atoum/blob/master/classes/asserters/error.php#L28-31
* https://github.com/atoum/atoum/blob/master/classes/asserters/exception.php#L18-19
* https://github.com/atoum/atoum/blob/master/classes/asserters/extension.php#L30
* https://github.com/atoum/atoum/blob/master/classes/asserters/hash.php#L15-18
* https://github.com/atoum/atoum/blob/master/classes/asserters/integer.php#L16
* https://github.com/atoum/atoum/blob/master/classes/asserters/object.php#L16-20
* https://github.com/atoum/atoum/blob/master/classes/asserters/phpArray.php#L28
* https://github.com/atoum/atoum/blob/master/classes/asserters/phpClass.php#L19-21
* https://github.com/atoum/atoum/blob/master/classes/asserters/string.php#L23-27
* https://github.com/atoum/atoum/blob/master/classes/asserters/variable.php#L36-41
* https://github.com/atoum/atoum/blob/master/classes/asserters/adapter/call.php#L39-45

and all derivated asserters.

**Comment by Grummfy** [comment]
On peut le dire de toutes assertions sans paramètre?

**Comment by Grummfy** [comment]
ping @jubianchi ?

**Comment by Hywan** [comment]
@Grummfy Not sure. I don't think so.

**Comment by Grummfy** [comment]
Oki I wait answer from @jubianchi

**Comment by jubianchi** [comment]
> On peut le dire de toutes assertions sans paramètre?

@Grummfy oui en théorie, toute assertion qui n'a pas de paramètre obligatoire doit pouvoir être appelée sans paranthèses

**Comment by Grummfy** [comment]
Merci.
Vous voyez cela comme un chapitre a part ou bien on mettrait un exemple ou une simple note de rappel partout?

**Comment by Hywan** [comment]
Une simple note.

**Comment by jubianchi** [comment]
+1 pour une petite note

**Comment by Grummfy** [comment]
thanks.
