### ISSUE TITLE
$this->exception is not documented

### ISSUE THREAD

**Issue by Hywan** [atoum/atoum-documentation#67]
See https://github.com/atoum/atoum/issues/424#issuecomment-71478904.

**Comment by Grummfy** [comment]
Là je vais avoir besoin d'un peu de détails pour comprendre (ou de relire à une heure descente).

**Comment by Grummfy** [comment]
What's the the difference with http://docs.atoum.org/fr/latest/assertions.html?highlight=exception#exception ? @mageekguy ?

**Comment by mageekguy** [comment]
technically there is no difference.
`this->exception` is just syntaxic sugar: it's a shortcut to the last exception instance watched by `->exception()` asserter.

**Comment by Grummfy** [comment]
so $this->exception(function(){ somethingthatCreateException()})->isEqualTo($this->exception) ?

**Comment by mageekguy** [comment]
I would say even more: `->isIdenticalTo($this->exception)`.

**Comment by Grummfy** [comment]
perfect.
thanks
