### ISSUE TITLE
how to translate? How to add page/... => how to contribute

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum-documentation#68]
It will be very usefull if we have a guide that guide how to contribute to this documentation.
With the readme, we know how to build the doc, but not how to contribute to it : 
* how(process/stuff to respect/....) to add new page/info/...?
* how(process/stuff to respect/....) to add new language?
* how(process/stuff to respect/....) to maintain other language that french (the reference)?

**Comment by marmotz** [comment]
Yes you're right and while you've just submit a PR, you should write this guide :)

**Comment by Grummfy** [comment]
Nope, because I think this is overall internall stuff (except for adding page, for this one I can do)
