### ISSUE TITLE
key api crowdin

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum-documentation#71]
Hello,
I think it could be intresting to check how to remove the translation key from the config file of crowdin. Because when we push the documentation it's always @marmotz that push it to crowdin...

**Comment by marmotz** [comment]
We should create an atoum account

**Comment by Grummfy** [comment]
@jubianchi , @Hywan or @mageekguy any comment on it?

**Comment by Hywan** [comment]
@Grummfy I don't know this service and I don't know how the documentation works :-p.

**Comment by Grummfy** [comment]
@Hywan :
Well, for now: 
1. adding files in french => upload it to crowdin (through crowndin-cli tools : crowdin-cli upload sources )
2. translate it on this plateform (easier than trying locally, because you can see the original file, change one sentence, have suggestion, etc)
3. download translated files (crowndin-cli download)
4. rebuild the documentation (php builddoc)
5. admire your work

**Comment by Hywan** [comment]
@Grummfy And?

**Comment by marmotz** [comment]
@Hywan and because you don't know how the documentation works, Grummfy explain you the full process.
Thank you Grummfy.

**Comment by Hywan** [comment]
@marmotz …
@Grummfy And… it is not possible to define another commiter?

**Comment by jubianchi** [comment]
@marmotz :+1: for an atoum account on crowdin. DOing so, we'll be able to manage committers with ease.

BTW, thans @marmotz and @Grummfy for the recent work! :beers:

**Comment by marmotz** [comment]
@jubianchi I've just merged the excellent work of Grummfy

**Comment by Grummfy** [comment]
Lol my crapy translation is now know as "excellent work".
BTW I have a bit help from @vonglasow .

Oki, so @marmotz you create a crowdin account for atoum?  Next we change api key, and everybody is happy about this topics.

**Comment by marmotz** [comment]
Sorry, but I have neither the time nor the desire to create it.

**Comment by Grummfy** [comment]
I have contacted crowdin to get an account for atoum instead of personal account

**Comment by Grummfy** [comment]
I got the access, I need to crea

**Comment by marmotz** [comment]
In 2012, @mageekguy created a documentation@atoum.org email group for @geraldcroes and me.
I don't if it still works and who is in this group, today.

**Comment by Grummfy** [comment]
* crowdin account created with docs@atoum.org
* asked how to transfer owner of account from @marmotz to atoum account.
* then we will update api key.
