### ISSUE TITLE
Impossible to send translated file to crowdin

### ISSUE THREAD

**Issue by Grummfy** [atoum/atoum-documentation#92]
crowdin-cli upload translations

Warning: Skip `/source/en/index.rst'
Warning: Skip `/source/en/cookbook.rst'
Warning: Skip `/source/en/extensions.rst'
Warning: Skip `/source/en/contribute.rst'
Warning: Skip `/source/en/getting_started.rst'
Warning: Skip `/source/en/written_help.rst'
Warning: Skip `/source/en/asserters.rst'
Warning: Skip `/source/en/asserters/exception.inc.rst'
Warning: Skip `/source/en/asserters/dateTime.inc.rst'
Warning: Skip `/source/en/asserters/boolean.inc.rst'
Warning: Skip `/source/en/asserters/castToString.inc.rst'
Warning: Skip `/source/en/asserters/mock.inc.rst'
Warning: Skip `/source/en/asserters/output.inc.rst'
Warning: Skip `/source/en/asserters/sizeOf.inc.rst'
Warning: Skip `/source/en/asserters/utf8String.inc.rst'
Warning: Skip `/source/en/asserters/stream.inc.rst'
Warning: Skip `/source/en/asserters/class.inc.rst'
Warning: Skip `/source/en/asserters/afterDestructionOf.inc.rst'
Warning: Skip `/source/en/asserters/variable.inc.rst'
Warning: Skip `/source/en/asserters/float.inc.rst'
Warning: Skip `/source/en/asserters/dateInterval.inc.rst'
Warning: Skip `/source/en/asserters/mysqlDateTime.inc.rst'
Warning: Skip `/source/en/asserters/array.inc.rst'
Warning: Skip `/source/en/asserters/integer.inc.rst'
Warning: Skip `/source/en/asserters/error.inc.rst'
Warning: Skip `/source/en/asserters/string.inc.rst'
Warning: Skip `/source/en/asserters/hash.inc.rst'
Warning: Skip `/source/en/asserters/object.inc.rst'
Warning: Skip `/source/en/quotes.rst'
Warning: Skip `/source/en/launch_test.rst'
Warning: Skip `/source/en/option_cli.rst'
Warning: Skip `/source/en/ide.rst'
Warning: Skip `/source/en/having_fun_with_atoum.rst'

**Comment by marmotz** [comment]
Well, I don't know why...

**Comment by Grummfy** [comment]
Oki, I think you know better the tools.
Can you check, or did I need to check?

**Comment by marmotz** [comment]
Honestly, I do not know :-/
I think I had the same problem at the beginning, but I do not remember. Sorry.

**Comment by Grummfy** [comment]
Well, the solution of crowdin support => copy manually what have been changed ...
